---
- name: Launch application container
  community.docker.docker_container:
    name: java-app
    image: romainnn/devops_app:latest
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/db"
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
    networks:
      - name: app-network
      - name: proxy-network
    pull: true
    state: started
    restart_policy: always
