---
- name: Launch proxy container
  community.docker.docker_container:
    name: apache
    image: romainnn/devops_proxy:latest
    ports:
      - "80:80"
    networks:
      - name: proxy-network
    state: started
    restart_policy: always
