name: CI devops 2025
on:
  push:
    branches: main 
  pull_request:

jobs:
  maven:
      runs-on: ubuntu-24.04
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and push Maven
        run : mvn clean verify
      - name: Use sonarcloud
        run : mvn -B verify sonar:sonar -Dsonar.projectKey=REN-Romain_TP_DevOps -Dsonar.organization=ren-romain -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file pom.xml
  application_image:
      runs-on: ubuntu-24.04
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set version
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build image and push application
        uses: docker/build-push-action@v6
        with:
          context: .
          tags:  |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_app:${{ steps.vars.outputs.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  database_image:
      runs-on: ubuntu-24.04
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set version
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./postgres
          tags:  |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_app:${{ steps.vars.outputs.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  httpd_image:
      runs-on: ubuntu-24.04
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set version
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build image and httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http
          tags:  |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_app:${{ steps.vars.outputs.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
